-- MySQL Script generated by MySQL Workbench
-- Sat Dec 31 16:19:15 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema nounouetnous
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `nounouetnous` ;

-- -----------------------------------------------------
-- Schema nounouetnous
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nounouetnous` DEFAULT CHARACTER SET utf8mb4 ;
USE `nounouetnous` ;

-- -----------------------------------------------------
-- Table `nounouetnous`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nounouetnous`.`role` ;

CREATE TABLE IF NOT EXISTS `nounouetnous`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nounouetnous`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nounouetnous`.`user` ;

CREATE TABLE IF NOT EXISTS `nounouetnous`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lastname` VARCHAR(45) NULL,
  `firstname` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `hashed_password` VARCHAR(100) NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`id`, `role_id`),
  INDEX `fk_user_role1_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `nounouetnous`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nounouetnous`.`kid`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nounouetnous`.`kid` ;

CREATE TABLE IF NOT EXISTS `nounouetnous`.`kid` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lastname` VARCHAR(45) NULL,
  `firstname` VARCHAR(45) NULL,
  `birthdate` DATE NULL,
  `parent` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `parent_idx` (`parent` ASC) VISIBLE,
  CONSTRAINT `parent`
    FOREIGN KEY (`parent`)
    REFERENCES `nounouetnous`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nounouetnous`.`contract`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nounouetnous`.`contract` ;

CREATE TABLE IF NOT EXISTS `nounouetnous`.`contract` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `kid_id` INT NOT NULL,
  `caregiver` VARCHAR(45) NULL,
  `starting_date` DATE NULL,
  `ending_date` DATE NULL,
  `weeks_per_year` INT NULL,
  `monday_start` TIME NULL,
  `monday_end` TIME NULL,
  `tuesday_start` TIME NULL,
  `tuesday_end` TIME NULL,
  `wednesday_start` TIME NULL,
  `wednesday_end` TIME NULL,
  `thursday_start` TIME NULL,
  `thursday_end` TIME NULL,
  `friday_start` TIME NULL,
  `friday_end` TIME NULL,
  `price_hour` FLOAT NULL,
  `price_over_hour` FLOAT NULL,
  `price_household` FLOAT NULL,
  `price_long_household` FLOAT NULL,
  `price_meal` FLOAT NULL,
  `price_snack` FLOAT NULL,
  `days_off` FLOAT NULL,
  `regulation_at_end` FLOAT NULL,
  PRIMARY KEY (`id`, `kid_id`),
  INDEX `fk_contract_kid1_idx` (`kid_id` ASC) VISIBLE,
  CONSTRAINT `fk_contract_kid1`
    FOREIGN KEY (`kid_id`)
    REFERENCES `nounouetnous`.`kid` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nounouetnous`.`user_contract`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nounouetnous`.`user_contract` ;

CREATE TABLE IF NOT EXISTS `nounouetnous`.`user_contract` (
  `is_main` TINYINT(1) NULL,
  `user_id` INT NOT NULL,
  `contract_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `contract_id`),
  INDEX `fk_user_contract_contract1_idx` (`contract_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_contract_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `nounouetnous`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_contract_contract1`
    FOREIGN KEY (`contract_id`)
    REFERENCES `nounouetnous`.`contract` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nounouetnous`.`event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nounouetnous`.`event` ;

CREATE TABLE IF NOT EXISTS `nounouetnous`.`event` (
  `id` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  `is_paid` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nounouetnous`.`contract_event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nounouetnous`.`contract_event` ;

CREATE TABLE IF NOT EXISTS `nounouetnous`.`contract_event` (
  `contract_id` INT NOT NULL,
  `event_id` INT NOT NULL,
  `date` DATE NULL,
  `duration` TIME NULL,
  PRIMARY KEY (`contract_id`, `event_id`),
  INDEX `fk_contract_event_event1_idx` (`event_id` ASC) VISIBLE,
  CONSTRAINT `fk_contract_event_contract1`
    FOREIGN KEY (`contract_id`)
    REFERENCES `nounouetnous`.`contract` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contract_event_event1`
    FOREIGN KEY (`event_id`)
    REFERENCES `nounouetnous`.`event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- Data for table `nounouetnous`.`role`

START TRANSACTION;
USE `nounouetnous`;
INSERT INTO `nounouetnous`.`role` (`id`, `role`) VALUES (1, 'admin');
INSERT INTO `nounouetnous`.`role` (`id`, `role`) VALUES (2, 'parent');
INSERT INTO `nounouetnous`.`role` (`id`, `role`) VALUES (3, 'nounou');

COMMIT;

-- Data for table `nounouetnous`.`user`

START TRANSACTION;
USE `nounouetnous`;
INSERT INTO `nounouetnous`.`user` (`id`, `lastname`, `firstname`, `email`, `hashed_password`, `role_id`) VALUES (1, 'Dupont', 'Damien', 'damiendupont.dd@gmail.com', NULL, 2);
INSERT INTO `nounouetnous`.`user` (`id`, `lastname`, `firstname`, `email`, `hashed_password`, `role_id`) VALUES (2, 'Admin', 'Admin', 'admin@admin.com', NULL, 1);
INSERT INTO `nounouetnous`.`user` (`id`, `lastname`, `firstname`, `email`, `hashed_password`, `role_id`) VALUES (3, 'Parent', 'Fictif', 'parent@fictif.com', NULL, 2);

COMMIT;

-- Data for table `nounouetnous`.`kid`

START TRANSACTION;
USE `nounouetnous`;
INSERT INTO `nounouetnous`.`kid` (`id`, `lastname`, `firstname`, `birthdate`, `parent`) VALUES (DEFAULT, 'Dupont', 'Margot', '2020/10/18',1);
INSERT INTO `nounouetnous`.`kid` (`id`, `lastname`, `firstname`, `birthdate`, `parent`) VALUES (DEFAULT, 'Fictif', 'Bidule', '2022/01/01',1);

COMMIT;

-- Data for table `nounouetnous`.`contract`

START TRANSACTION;
USE `nounouetnous`;
INSERT INTO `nounouetnous`.`contract` (`id`, `kid_id`, `caregiver`, `starting_date`, `ending_date`, `weeks_per_year`, `monday_start`, `monday_end`, `tuesday_start`, `tuesday_end`, `wednesday_start`, `wednesday_end`, `thursday_start`, `thursday_end`, `friday_start`, `friday_end`, `price_hour`, `price_over_hour`, `price_household`, `price_long_household`, `price_meal`, `price_snack`, `days_off`, `regulation_at_end`) VALUES (DEFAULT, 1, 'Isa', '2022/09/01', NULL, 36, '7:45', '17:15', '7:45', '17:15', NULL, NULL, '7:45', '17:15', '7:45', '17:15', 4, 4, 3.39, 3.39, 3.50, 1.50, 0, NULL);

COMMIT;

-- Data for table `nounouetnous`.`user_contract`

START TRANSACTION;
USE `nounouetnous`;
INSERT INTO `nounouetnous`.`event`(`id`, `type`, `is_paid`) VALUES (1, 'garde prévue', 1);
INSERT INTO `nounouetnous`.`event`(`id`, `type`, `is_paid`) VALUES (2, 'garde imprévue', 1);
INSERT INTO `nounouetnous`.`event`(`id`, `type`, `is_paid`) VALUES (3, 'heures supplémentaires', 1);
INSERT INTO `nounouetnous`.`event`(`id`, `type`, `is_paid`) VALUES (4, 'absence nounou journée', 0);
INSERT INTO `nounouetnous`.`event`(`id`, `type`, `is_paid`) VALUES (5, 'absence nounou heures', 0);
INSERT INTO `nounouetnous`.`event`(`id`, `type`, `is_paid`) VALUES (6, 'absence enfant journée', 1);
INSERT INTO `nounouetnous`.`event`(`id`, `type`, `is_paid`) VALUES (7, 'absence enfant malade', 0);
INSERT INTO `nounouetnous`.`event`(`id`, `type`, `is_paid`) VALUES (8, 'formation nounou', 1);
INSERT INTO `nounouetnous`.`event`(`id`, `type`, `is_paid`) VALUES (9, 'férié payé', 1);
INSERT INTO `nounouetnous`.`event`(`id`, `type`, `is_paid`) VALUES (10, 'férié non payé', 0);
INSERT INTO `nounouetnous`.`event`(`id`, `type`, `is_paid`) VALUES (11, 'congés payés', 1);
INSERT INTO `nounouetnous`.`event`(`id`, `type`, `is_paid`) VALUES (12, 'congés sans solde', 0);

COMMIT;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
